apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-practice-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-practice-app
  template:
    metadata:
      labels:
        app: devops-practice-app
    spec:
      containers:
      - name: devops-practice-app
        image: your-docker-username/devops-practice-app:latest
        ports:
        - containerPort: 3000
