apiVersion: v1
kind: Service
metadata:
  name: devops-practice-service
spec:
  selector:
    app: devops-practice-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
